
SCREEN_TITLE = "Slime Survival"

# ---Sizing & Scaling 
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

TILE_PIXEL_SIZE = 32
TILE_SCALING = 1

PLAYER_PIXEL_SIZE = 16
PLAYER_SCALING = 1
GRID_PIXEL_SIZE = TILE_PIXEL_SIZE * TILE_SCALING

# --- Margin 
VIEWPORT_MARGIN_TOP = 60
VIEWPORT_MARGIN_BOTTOM = 60
VIEWPORT_RIGHT_MARGIN = 270
VIEWPORT_LEFT_MARGIN = 270

# --- Player
MOVEMENT_SPEED = 5

# --- Path 

MAP_PATH = "./slime_survival/tile_world/map.json"
PLAYER_PATH = "./slime_survival/sprite/Player/"